name: SelfKare
favicon: null
layout_spectrum: 0.10360749089159071
typography_spectrum: 0.22383399750106037
title: Fitness and Yoga Equipment for sale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29abe2'
    - '#83c121'
    - '#ffffff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
